# -*- coding: utf-8 -*-

from . import models
from . import account_hacienda
from . import account_journal
from . import account_move
from . import account_move_func
from . import account_move_reversal
from . import account_payment_term
from . import account_tax
from . import activity_code
from . import activity_code_func
from . import electronic_doc
from . import electronic_doc_func
from . import electronic_doc_line
from . import cabys_code
from . import product_product
from . import product_template
from . import ir_sequence
from . import res_company
from . import res_company_func
from . import res_partner
from . import uom_uom
from . import wizard_agregar_contabilidad
from . import account_move_otros_line
from . import account_move_inforef_line
from . import account_move_attachment_line
from . import account_fiscal_position
from . import res_partner_emails_extra
from . import res_partner_otros_line